#pragma once
#include "../Graphics/Texture.h"

enum Direction
{
	DOWN,
	RIGHT,
	UP,
	LEFT
};

enum class EntityType
{
	PLAYER = 0,
	GHOST = 1,
	BLOCK = 2
};

enum TextureName
{
	TEXTURE_PLAYER,
	TEXTURE_WALL,
	TEXTURE_COIN,
	TEXTURE_ENEMY,
	TEXTURE_BG,
	TEXTURE_GROUND,
	TEXTURE_START_BUTTON,
	TEXTURE_EXIT_BUTTON,
	TEXTURE_MENU_BUTTON,
	TEXTURE_RESTART_BUTTON,
	TEXTURE_FLAG,
	TEXTURE_UNKNOWN,
	TEXTURE_START_BUTTON_HOVER,
	TEXTURE_EXIT_BUTTON_HOVER,
	TEXTURE_MENU_BUTTON_HOVER,
	TEXTURE_RESTART_BUTTON_HOVER,
	TEXTURE_DARKEN_BG,
	TEXTURE_TEXT_GJ,
	TEXTURE_CHARACTER_WALK_FRAME_0,
	TEXTURE_CHARACTER_WALK_FRAME_1,
	TEXTURE_CHARACTER_WALK_FRAME_2,
	TEXTURE_CHARACTER_WALK_FRAME_3,
	TEXTURE_CHARACTER_WALK_FRAME_4,
	TEXTURE_CHARACTER_WALK_FRAME_5,
	TEXTURE_CHARACTER_WALK_FRAME_6,
	TEXTURE_CHARACTER_WALK_FRAME_7,
	TEXTURE_CHARACTER_JUMP,
	TEXTURE_BG_MENU,
	TEXTURE_SPIKE_UP,
	TEXTURE_SPIKE_RIGHT,
	TEXTURE_SPIKE_DOWN,
	TEXTURE_SPIKE_LEFT,

	TEXTURE_LAST
};

struct Position
{
	float x;
	float y;
};

struct UniformPosition
{
	int x;
	int y;
};

struct Velocity
{
	float speedX;
	float speedY;
};

struct Sprite
{
	int x;
	int y;
	Texture* texture;
};
